apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    org: prod
    client: target
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: ngnix
